variables:
    XDG_CACHE_HOME: $CI_PROJECT_DIR/cache # Pip will cache under here
    PIP_INDEX_URL: https://devpi.mflocal.com/mfpkgs/dev/+simple/

cache:
    paths:
        - "$XDG_CACHE_HOME"

image: python:3.6-stretch

stages:
    - verify

.tox-task:
    before_script:
        - pip install tox

check-autoformatting:
    stage: verify
    extends: .tox-task
    script:
        - tox -e black
        - tox -e mypy
